<?php
/**
 * @file
 * farnet_pages.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function farnet_pages_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'pathauto_node_page_pattern';
  $strongarm->value = '[node:source:title]';
  $export['pathauto_node_page_pattern'] = $strongarm;

  return $export;
}
