<?php

/**
 * @file
 * Code for the Farnet Publication feature.
 */

include_once 'farnet_publication.features.inc';

/**
 * Implements hook_views_default_views_alter().
 */
function farnet_publication_views_default_views_alter(&$views) {
  if (isset($views['farnet_view_publication'])) {
    $publication = taxonomy_get_term_by_name('Publication');
    if ((isset($publication)) && (!empty($publication))) {
      $publication_term = current($publication);
      $tid_publication = $publication_term->tid;
      $views['farnet_view_publication']->display['page_publications']->display_options['filters']['field_type_of_publication_tid']['value'][$tid_publication] = $tid_publication;
    }
    $guide = taxonomy_get_term_by_name('Guide');
    if ((isset($guide)) && (!empty($guide))) {
      $guide_term = current($guide);
      $tid_guide = $guide_term->tid;
      $views['farnet_view_publication']->display['page_guides']->display_options['filters']['field_type_of_publication_tid']['value'][$tid_guide] = $tid_guide;
      $views['farnet_view_publication']->display['block_guides']->display_options['filters']['field_type_of_publication_tid']['value'][$tid_guide] = $tid_guide;
    }
    $magazine = taxonomy_get_term_by_name('FARNET Magazine');
    if ((isset($magazine)) && (!empty($magazine))) {
      $magazine_term = current($magazine);
      $tid_magazine = $magazine_term->tid;
      $views['farnet_view_publication']->display['page_magazines']->display_options['filters']['field_type_of_publication_tid']['value'][$tid_magazine] = $tid_magazine;
      $views['farnet_view_publication']->display['block_magazines']->display_options['filters']['field_type_of_publication_tid']['value'][$tid_magazine] = $tid_magazine;
    }
    $presentation = taxonomy_get_term_by_name('Presentation');
    if ((isset($presentation)) && (!empty($presentation))) {
      $presentation_term = current($presentation);
      $tid_presentation = $presentation_term->tid;
      $views['farnet_view_publication']->display['page_presentations']->display_options['filters']['field_type_of_publication_tid']['value'][$tid_presentation] = $tid_presentation;
      $views['farnet_view_publication']->display['block_presentations']->display_options['filters']['field_type_of_publication_tid']['value'][$tid_presentation] = $tid_presentation;
    }
    $technical_report = taxonomy_get_term_by_name('Technical report');
    if ((isset($technical_report)) && (!empty($technical_report))) {
      $technical_report_term = current($technical_report);
      $tid_technical_report = $technical_report_term->tid;
      $views['farnet_view_publication']->display['page_technical_reports']->display_options['filters']['field_type_of_publication_tid']['value'][$tid_technical_report] = $tid_technical_report;
    }
  }
}
