<?php

/**
 * @file
 * Code for the Farnet Media Gallery feature.
 */

include_once 'farnet_mediagallery.features.inc';

/**
 * Implements hook_COMPONENT_alter().
 *
 * COMPONENT = field_default_field_instances.
 */
function farnet_mediagallery_field_default_field_instances_alter(&$fields) {
  $fname = "node-nexteuropa_mediagallery-field_media_upload";
  if (isset($fields[$fname])) {
    if (isset($fields[$fname]['widget']['settings']['browser_plugins']['media_default--media_browser_1'])) {
      $fields[$fname]['widget']['settings']['browser_plugins']['media_default--media_browser_1'] = "media_default--media_browser_1";
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function farnet_mediagallery_form_node_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'nexteuropa_mediagallery_node_form') {
    $form['group_content_access'][LANGUAGE_NONE]['#required'] = FALSE;
  }
}
