<?php

/**
 * @file
 * Code for the Farnet GP Project feature.
 */

include_once 'farnet_gp_project.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function farnet_gp_project_form_gp_project_node_form_alter(&$form, &$form_state, $form_id) {
  $path = drupal_get_path('module', 'farnet_gp_project');
  $form['#attached']['js'] = [
    [
      'data' => $path . '/js/farnet_gp_project.js',
      'type' => 'file',
      'scope' => 'footer',
      'weight' => 100,
    ],
  ];
}
