<?php

/**
 * @file
 * Code for the MyFarnet News feature.
 */

include_once 'myfarnet_news.features.inc';

/**
 * Implements hook_menu().
 */
function myfarnet_news_menu() {
  $items = array();

  $items['community/%community/news'] = array(
    'title' => 'News',
    'page callback' => 'farnet_communities_display_views',
    'page arguments' => array('my_farnet_news', 'page_1', 1),
    'access callback' => '_farnet_communities_ct_page_access',
    'access arguments' => array('access private area', 1, 'myfarnet_news'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-community-menu',
    'weight' => 3,
    'file' => 'farnet_communities.callback.inc',
    'file path' => drupal_get_path('module', 'farnet_communities'),
  );

  return $items;
}

/**
 * Implements hook_COMPONENT_alter().
 *
 * COMPONENT = field_default_field_bases.
 */
function myfarnet_news_field_default_field_bases_alter(&$fields) {
  if (isset($fields['field_related_documents'])) {
    $fields['field_related_documents']['settings']['display_default'] = 0;
    $fields['field_related_documents']['settings']['display_field'] = 0;
  }
}
