<?php

/**
 * @file
 * Code for the MyFarnet Cooperation Idea feature.
 */

include_once 'myfarnet_cooperation_idea.features.inc';

/**
 * @param $plugins
 */
function myfarnet_cooperation_idea_media_browser_plugins_alter(&$plugins) {
  dpm($plugins);
  //unset($plugins['media_default--media_browser_1']);
  //unset($plugins['media_internet']);
  //unset($plugins['media_default--media_browser_my_files']);
}
