<?php

/**
 * @file
 * Install, uninstall, schema and update hooks for farnet factsheet country module.
 */

/**
 * Implements hook_enable().
 */
function farnet_factsheet_country_enable() {
  drupal_set_message(t('The FARNET Factsheet Country feature is now active on your site.'));
}

/**
 * Implements hook_disable().
 */
function farnet_factsheet_country_disable() {
  drupal_set_message(t('The FARNET Factsheet Country feature is now disabled on your site.'));
}