<?php
/**
 * @file
 * Code for the Farnet Factsheet Country feature.
 */

include_once 'farnet_factsheet_country.features.inc';

/**
 * Implements hook_COMPONENT_alter().
 */
function farnet_factsheet_country_strongarm_alter(&$variables) {
  if(isset($variables['pathauto_node_factsheet_country_pattern'])) {
    $variables['pathauto_node_factsheet_country_pattern']->value = "on-the-ground/country-factsheets/[node:source:title]";
  }
}
