<?php
/**
 * @file
 * Code for the Farnet FAQ feature.
 */

include_once 'farnet_faq.features.inc';

/**
 * Implements hook_field_group_info_alter().
 */
function farnet_faq_field_group_info_alter($groups) {
  if (!empty($groups['group_ne_faq_content|node|nexteuropa_faq|form'])) {
    $groups['group_ne_faq_content|node|nexteuropa_faq|form']->data['children'][] = 'field_id';
    $groups['group_ne_faq_content|node|nexteuropa_faq|form']->data['children'][] = 'field_short_title';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function farnet_faq_form_nexteuropa_faq_node_form_alter(&$form, &$form_state, $form_id) {
  $path = drupal_get_path('module', 'farnet_faq');
  $form['#attached']['js'] = [
    [
      'data' => $path . '/js/farnet_faq.js',
      'type' => 'file',
      'scope' => 'footer',
      'weight' => 100,
    ],
  ];
}

/**
 * Implements hook_COMPONENT_alter().
 *
 * COMPONENT = field_default_field_instances.
 */
function farnet_faq_field_default_field_instances_alter(&$fields) {

  if (isset($fields['node-nexteuropa_faq-title_field'])) {
    if (isset($fields['node-nexteuropa_faq-title_field']['display'])) {
      $fields['node-nexteuropa_faq-title_field']['display']['teaser']['label'] = "hidden";
      $fields['node-nexteuropa_faq-title_field']['display']['teaser']['module'] = "text";
      $fields['node-nexteuropa_faq-title_field']['display']['teaser']['settings'] = array();
      $fields['node-nexteuropa_faq-title_field']['display']['teaser']['type'] = "text_plain";
      /* $fields['node-nexteuropa_faq-title_field']['display']['teaser']['type'] = "title_linked";*/
      $fields['node-nexteuropa_faq-title_field']['display']['teaser']['weight'] = 0;
    }
  }

  if (isset($fields['node-nexteuropa_faq-field_ne_body'])) {
    if (isset($fields['node-nexteuropa_faq-field_ne_body']['display'])) {
      $fields['node-nexteuropa_faq-field_ne_body']['display']['teaser']['label'] = "hidden";
      $fields['node-nexteuropa_faq-field_ne_body']['display']['teaser']['module'] = "text";
      $fields['node-nexteuropa_faq-field_ne_body']['display']['teaser']['settings'] = array();
      $fields['node-nexteuropa_faq-field_ne_body']['display']['teaser']['type'] = "text_default";
      $fields['node-nexteuropa_faq-field_ne_body']['display']['teaser']['weight'] = 2;
    }
  }
}

/**
 * Implements hook_views_default_views_alter().
 */
function farnet_faq_views_default_views_alter(&$views) {
  if (isset($views['ne_faq'])) {

    $view = $views['ne_faq'];

    /* Display: faq */
    $handler = $view->new_display('page', 'faq', 'page_faq');
    $handler->display->display_options['defaults']['title'] = FALSE;
    $handler->display->display_options['title'] = 'FAQs';
    $handler->display->display_options['defaults']['fields'] = FALSE;
    /* Field: Content: Title */
    $handler->display->display_options['fields']['title']['id'] = 'title';
    $handler->display->display_options['fields']['title']['table'] = 'node';
    $handler->display->display_options['fields']['title']['field'] = 'title';
    $handler->display->display_options['fields']['title']['label'] = '';
    $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
    $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
    /* Field: Content: Edit link */
    $handler->display->display_options['fields']['edit_node']['id'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['table'] = 'views_entity_node';
    $handler->display->display_options['fields']['edit_node']['field'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['label'] = '';
    $handler->display->display_options['fields']['edit_node']['exclude'] = TRUE;
    $handler->display->display_options['fields']['edit_node']['element_label_colon'] = FALSE;
    /* Field: Content: Body */
    $handler->display->display_options['fields']['field_ne_body']['id'] = 'field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['table'] = 'field_data_field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['field'] = 'field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['label'] = '';
    $handler->display->display_options['fields']['field_ne_body']['element_label_colon'] = FALSE;
    /* Field: Content: All taxonomy terms */
    $handler->display->display_options['fields']['term_node_tid']['id'] = 'term_node_tid';
    $handler->display->display_options['fields']['term_node_tid']['table'] = 'node';
    $handler->display->display_options['fields']['term_node_tid']['field'] = 'term_node_tid';
    $handler->display->display_options['fields']['term_node_tid']['label'] = '';
    $handler->display->display_options['fields']['term_node_tid']['exclude'] = TRUE;
    $handler->display->display_options['fields']['term_node_tid']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['term_node_tid']['limit'] = TRUE;
    $handler->display->display_options['fields']['term_node_tid']['vocabularies'] = array(
      'faq_categories' => 'faq_categories',
      'classification' => 0,
      'tags' => 0,
    );
    $handler->display->display_options['path'] = 'tools/faq';

    /* Display: faq-clld-overview */
    $handler = $view->new_display('page', 'faq-clld-overview', 'page_faq_clld_overview');
    $handler->display->display_options['defaults']['title'] = FALSE;
    $handler->display->display_options['title'] = 'FAQ - CLLD overview';
    $handler->display->display_options['defaults']['fields'] = FALSE;
    /* Field: Content: Title */
    $handler->display->display_options['fields']['title']['id'] = 'title';
    $handler->display->display_options['fields']['title']['table'] = 'node';
    $handler->display->display_options['fields']['title']['field'] = 'title';
    $handler->display->display_options['fields']['title']['label'] = '';
    $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
    $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
    /* Field: Content: Edit link */
    $handler->display->display_options['fields']['edit_node']['id'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['table'] = 'views_entity_node';
    $handler->display->display_options['fields']['edit_node']['field'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['label'] = '';
    $handler->display->display_options['fields']['edit_node']['exclude'] = TRUE;
    $handler->display->display_options['fields']['edit_node']['element_label_colon'] = FALSE;
    /* Field: Content: Body */
    $handler->display->display_options['fields']['field_ne_body']['id'] = 'field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['table'] = 'field_data_field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['field'] = 'field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['label'] = '';
    $handler->display->display_options['fields']['field_ne_body']['element_label_colon'] = FALSE;
    /* Field: Content: All taxonomy terms */
    $handler->display->display_options['fields']['term_node_tid']['id'] = 'term_node_tid';
    $handler->display->display_options['fields']['term_node_tid']['table'] = 'node';
    $handler->display->display_options['fields']['term_node_tid']['field'] = 'term_node_tid';
    $handler->display->display_options['fields']['term_node_tid']['label'] = '';
    $handler->display->display_options['fields']['term_node_tid']['exclude'] = TRUE;
    $handler->display->display_options['fields']['term_node_tid']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['term_node_tid']['limit'] = TRUE;
    $handler->display->display_options['fields']['term_node_tid']['vocabularies'] = array(
      'faq_categories' => 'faq_categories',
      'classification' => 0,
      'tags' => 0,
    );
    $handler->display->display_options['defaults']['filter_groups'] = FALSE;
    $handler->display->display_options['defaults']['filters'] = FALSE;
    /* Filter criterion: Content: Published */
    $handler->display->display_options['filters']['status']['id'] = 'status';
    $handler->display->display_options['filters']['status']['table'] = 'node';
    $handler->display->display_options['filters']['status']['field'] = 'status';
    $handler->display->display_options['filters']['status']['value'] = 1;
    $handler->display->display_options['filters']['status']['group'] = 1;
    $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
    /* Filter criterion: Content: Type */
    $handler->display->display_options['filters']['type']['id'] = 'type';
    $handler->display->display_options['filters']['type']['table'] = 'node';
    $handler->display->display_options['filters']['type']['field'] = 'type';
    $handler->display->display_options['filters']['type']['value'] = array(
      'nexteuropa_faq' => 'nexteuropa_faq',
    );
    /* Filter criterion: Content: Categories (field_ne_faq_categories) */
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['id'] = 'field_ne_faq_categories_tid';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['table'] = 'field_data_field_ne_faq_categories';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['field'] = 'field_ne_faq_categories_tid';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['value'] = array();
    $term = taxonomy_get_term_by_name('CLLD overview');
    if ((isset($term)) && (!empty($term))) {
      $filter_term = current($term);
      $tid_term = $filter_term->tid;
      $handler->display->display_options['filters']['field_ne_faq_categories_tid']['value'][$tid_term] = $tid_term;
    }
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['type'] = 'select';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['vocabulary'] = 'faq_categories';
    $handler->display->display_options['path'] = 'tools/faq/clld-overview';
    /*
    $term = taxonomy_get_term_by_name('CLLD overview');
    if ((isset($term)) && (!empty($term))) {
      $filter_term = current($term);
      $tid_term = $filter_term->tid;
      $views['ne_faq']->display['page_faq_clld_overview']->display_options['filters']['field_ne_faq_categories_tid']['value'][$tid_term] = $tid_term;
    }
    */

    /* Display: faq-eligibility */
    $handler = $view->new_display('page', 'faq-eligibility', 'page_faq_eligibility');
    $handler->display->display_options['defaults']['title'] = FALSE;
    $handler->display->display_options['title'] = 'FAQ - Eligibility';
    $handler->display->display_options['defaults']['fields'] = FALSE;
    /* Field: Content: Title */
    $handler->display->display_options['fields']['title']['id'] = 'title';
    $handler->display->display_options['fields']['title']['table'] = 'node';
    $handler->display->display_options['fields']['title']['field'] = 'title';
    $handler->display->display_options['fields']['title']['label'] = '';
    $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
    $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
    /* Field: Content: Edit link */
    $handler->display->display_options['fields']['edit_node']['id'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['table'] = 'views_entity_node';
    $handler->display->display_options['fields']['edit_node']['field'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['label'] = '';
    $handler->display->display_options['fields']['edit_node']['exclude'] = TRUE;
    $handler->display->display_options['fields']['edit_node']['element_label_colon'] = FALSE;
    /* Field: Content: Body */
    $handler->display->display_options['fields']['field_ne_body']['id'] = 'field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['table'] = 'field_data_field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['field'] = 'field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['label'] = '';
    $handler->display->display_options['fields']['field_ne_body']['element_label_colon'] = FALSE;
    /* Field: Content: All taxonomy terms */
    $handler->display->display_options['fields']['term_node_tid']['id'] = 'term_node_tid';
    $handler->display->display_options['fields']['term_node_tid']['table'] = 'node';
    $handler->display->display_options['fields']['term_node_tid']['field'] = 'term_node_tid';
    $handler->display->display_options['fields']['term_node_tid']['label'] = '';
    $handler->display->display_options['fields']['term_node_tid']['exclude'] = TRUE;
    $handler->display->display_options['fields']['term_node_tid']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['term_node_tid']['limit'] = TRUE;
    $handler->display->display_options['fields']['term_node_tid']['vocabularies'] = array(
      'faq_categories' => 'faq_categories',
      'classification' => 0,
      'tags' => 0,
    );
    $handler->display->display_options['defaults']['filter_groups'] = FALSE;
    $handler->display->display_options['defaults']['filters'] = FALSE;
    /* Filter criterion: Content: Published */
    $handler->display->display_options['filters']['status']['id'] = 'status';
    $handler->display->display_options['filters']['status']['table'] = 'node';
    $handler->display->display_options['filters']['status']['field'] = 'status';
    $handler->display->display_options['filters']['status']['value'] = 1;
    $handler->display->display_options['filters']['status']['group'] = 1;
    $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
    /* Filter criterion: Content: Type */
    $handler->display->display_options['filters']['type']['id'] = 'type';
    $handler->display->display_options['filters']['type']['table'] = 'node';
    $handler->display->display_options['filters']['type']['field'] = 'type';
    $handler->display->display_options['filters']['type']['value'] = array(
      'nexteuropa_faq' => 'nexteuropa_faq',
    );
    /* Filter criterion: Content: Categories (field_ne_faq_categories) */
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['id'] = 'field_ne_faq_categories_tid';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['table'] = 'field_data_field_ne_faq_categories';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['field'] = 'field_ne_faq_categories_tid';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['value'] = array();
    $term = taxonomy_get_term_by_name('Eligibility');
    if ((isset($term)) && (!empty($term))) {
      $filter_term = current($term);
      $tid_term = $filter_term->tid;
      $handler->display->display_options['filters']['field_ne_faq_categories_tid']['value'][$tid_term] = $tid_term;
    }
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['type'] = 'select';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['vocabulary'] = 'faq_categories';
    $handler->display->display_options['path'] = 'tools/faq/eligibility';
    /*
    $term = taxonomy_get_term_by_name('Eligibility');
    if ((isset($term)) && (!empty($term))) {
      $filter_term = current($term);
      $tid_term = $filter_term->tid;
      $views['ne_faq']->display['page_faq_eligibility']->display_options['filters']['field_ne_faq_categories_tid']['value'][$tid_term] = $tid_term;
    }
    */

    /* Display: faq-finance-administration */
    $handler = $view->new_display('page', 'faq-finance-administration', 'page_faq_finance_administration');
    $handler->display->display_options['defaults']['title'] = FALSE;
    $handler->display->display_options['title'] = 'FAQ - Finance and administration';
    $handler->display->display_options['defaults']['fields'] = FALSE;
    /* Field: Content: Title */
    $handler->display->display_options['fields']['title']['id'] = 'title';
    $handler->display->display_options['fields']['title']['table'] = 'node';
    $handler->display->display_options['fields']['title']['field'] = 'title';
    $handler->display->display_options['fields']['title']['label'] = '';
    $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
    $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
    /* Field: Content: Edit link */
    $handler->display->display_options['fields']['edit_node']['id'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['table'] = 'views_entity_node';
    $handler->display->display_options['fields']['edit_node']['field'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['label'] = '';
    $handler->display->display_options['fields']['edit_node']['exclude'] = TRUE;
    $handler->display->display_options['fields']['edit_node']['element_label_colon'] = FALSE;
    /* Field: Content: Body */
    $handler->display->display_options['fields']['field_ne_body']['id'] = 'field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['table'] = 'field_data_field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['field'] = 'field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['label'] = '';
    $handler->display->display_options['fields']['field_ne_body']['element_label_colon'] = FALSE;
    /* Field: Content: All taxonomy terms */
    $handler->display->display_options['fields']['term_node_tid']['id'] = 'term_node_tid';
    $handler->display->display_options['fields']['term_node_tid']['table'] = 'node';
    $handler->display->display_options['fields']['term_node_tid']['field'] = 'term_node_tid';
    $handler->display->display_options['fields']['term_node_tid']['label'] = '';
    $handler->display->display_options['fields']['term_node_tid']['exclude'] = TRUE;
    $handler->display->display_options['fields']['term_node_tid']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['term_node_tid']['limit'] = TRUE;
    $handler->display->display_options['fields']['term_node_tid']['vocabularies'] = array(
      'faq_categories' => 'faq_categories',
      'classification' => 0,
      'tags' => 0,
    );
    $handler->display->display_options['defaults']['filter_groups'] = FALSE;
    $handler->display->display_options['defaults']['filters'] = FALSE;
    /* Filter criterion: Content: Published */
    $handler->display->display_options['filters']['status']['id'] = 'status';
    $handler->display->display_options['filters']['status']['table'] = 'node';
    $handler->display->display_options['filters']['status']['field'] = 'status';
    $handler->display->display_options['filters']['status']['value'] = 1;
    $handler->display->display_options['filters']['status']['group'] = 1;
    $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
    /* Filter criterion: Content: Type */
    $handler->display->display_options['filters']['type']['id'] = 'type';
    $handler->display->display_options['filters']['type']['table'] = 'node';
    $handler->display->display_options['filters']['type']['field'] = 'type';
    $handler->display->display_options['filters']['type']['value'] = array(
      'nexteuropa_faq' => 'nexteuropa_faq',
    );
    /* Filter criterion: Content: Categories (field_ne_faq_categories) */
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['id'] = 'field_ne_faq_categories_tid';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['table'] = 'field_data_field_ne_faq_categories';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['field'] = 'field_ne_faq_categories_tid';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['value'] = array();
    $term = taxonomy_get_term_by_name('Finance and administration');
    if ((isset($term)) && (!empty($term))) {
      $filter_term = current($term);
      $tid_term = $filter_term->tid;
      $handler->display->display_options['filters']['field_ne_faq_categories_tid']['value'][$tid_term] = $tid_term;
    }
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['type'] = 'select';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['vocabulary'] = 'faq_categories';
    $handler->display->display_options['path'] = 'tools/faq/finance-administration';
    /*
    $term = taxonomy_get_term_by_name('Finance and administration');
    if ((isset($term)) && (!empty($term))) {
      $filter_term = current($term);
      $tid_term = $filter_term->tid;
      $views['ne_faq']->display['page_faq_finance_administration']->display_options['filters']['field_ne_faq_categories_tid']['value'][$tid_term] = $tid_term;
    }
    */

    /* Display: faq-flag-set-up */
    $handler = $view->new_display('page', 'faq-flag-set-up', 'page_faq_flag_set_up');
    $handler->display->display_options['defaults']['title'] = FALSE;
    $handler->display->display_options['title'] = 'FAQ - Setting up FLAGs';
    $handler->display->display_options['defaults']['fields'] = FALSE;
    /* Field: Content: Title */
    $handler->display->display_options['fields']['title']['id'] = 'title';
    $handler->display->display_options['fields']['title']['table'] = 'node';
    $handler->display->display_options['fields']['title']['field'] = 'title';
    $handler->display->display_options['fields']['title']['label'] = '';
    $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
    $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
    /* Field: Content: Edit link */
    $handler->display->display_options['fields']['edit_node']['id'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['table'] = 'views_entity_node';
    $handler->display->display_options['fields']['edit_node']['field'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['label'] = '';
    $handler->display->display_options['fields']['edit_node']['exclude'] = TRUE;
    $handler->display->display_options['fields']['edit_node']['element_label_colon'] = FALSE;
    /* Field: Content: Body */
    $handler->display->display_options['fields']['field_ne_body']['id'] = 'field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['table'] = 'field_data_field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['field'] = 'field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['label'] = '';
    $handler->display->display_options['fields']['field_ne_body']['element_label_colon'] = FALSE;
    /* Field: Content: All taxonomy terms */
    $handler->display->display_options['fields']['term_node_tid']['id'] = 'term_node_tid';
    $handler->display->display_options['fields']['term_node_tid']['table'] = 'node';
    $handler->display->display_options['fields']['term_node_tid']['field'] = 'term_node_tid';
    $handler->display->display_options['fields']['term_node_tid']['label'] = '';
    $handler->display->display_options['fields']['term_node_tid']['exclude'] = TRUE;
    $handler->display->display_options['fields']['term_node_tid']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['term_node_tid']['limit'] = TRUE;
    $handler->display->display_options['fields']['term_node_tid']['vocabularies'] = array(
      'faq_categories' => 'faq_categories',
      'classification' => 0,
      'tags' => 0,
    );
    $handler->display->display_options['defaults']['filter_groups'] = FALSE;
    $handler->display->display_options['defaults']['filters'] = FALSE;
    /* Filter criterion: Content: Published */
    $handler->display->display_options['filters']['status']['id'] = 'status';
    $handler->display->display_options['filters']['status']['table'] = 'node';
    $handler->display->display_options['filters']['status']['field'] = 'status';
    $handler->display->display_options['filters']['status']['value'] = 1;
    $handler->display->display_options['filters']['status']['group'] = 1;
    $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
    /* Filter criterion: Content: Type */
    $handler->display->display_options['filters']['type']['id'] = 'type';
    $handler->display->display_options['filters']['type']['table'] = 'node';
    $handler->display->display_options['filters']['type']['field'] = 'type';
    $handler->display->display_options['filters']['type']['value'] = array(
      'nexteuropa_faq' => 'nexteuropa_faq',
    );
    /* Filter criterion: Content: Categories (field_ne_faq_categories) */
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['id'] = 'field_ne_faq_categories_tid';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['table'] = 'field_data_field_ne_faq_categories';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['field'] = 'field_ne_faq_categories_tid';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['value'] = array();
    $term = taxonomy_get_term_by_name('Setting up FLAGs');
    if ((isset($term)) && (!empty($term))) {
      $filter_term = current($term);
      $tid_term = $filter_term->tid;
      $handler->display->display_options['filters']['field_ne_faq_categories_tid']['value'][$tid_term] = $tid_term;
    }
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['type'] = 'select';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['vocabulary'] = 'faq_categories';
    $handler->display->display_options['path'] = 'tools/faq/flag-set-up';
    /*
    $term = taxonomy_get_term_by_name('Setting up FLAGs');
    if ((isset($term)) && (!empty($term))) {
      $filter_term = current($term);
      $tid_term = $filter_term->tid;
      $views['ne_faq']->display['page_faq_flag_set_up']->display_options['filters']['field_ne_faq_categories_tid']['value'][$tid_term] = $tid_term;
    }
    */

    /* Display: faq-cooperation */
    $handler = $view->new_display('page', 'faq-cooperation', 'page_faq_cooperation');
    $handler->display->display_options['defaults']['title'] = FALSE;
    $handler->display->display_options['title'] = 'FAQ - Cooperation';
    $handler->display->display_options['defaults']['fields'] = FALSE;
    /* Field: Content: Title */
    $handler->display->display_options['fields']['title']['id'] = 'title';
    $handler->display->display_options['fields']['title']['table'] = 'node';
    $handler->display->display_options['fields']['title']['field'] = 'title';
    $handler->display->display_options['fields']['title']['label'] = '';
    $handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
    $handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
    /* Field: Content: Edit link */
    $handler->display->display_options['fields']['edit_node']['id'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['table'] = 'views_entity_node';
    $handler->display->display_options['fields']['edit_node']['field'] = 'edit_node';
    $handler->display->display_options['fields']['edit_node']['label'] = '';
    $handler->display->display_options['fields']['edit_node']['exclude'] = TRUE;
    $handler->display->display_options['fields']['edit_node']['element_label_colon'] = FALSE;
    /* Field: Content: Body */
    $handler->display->display_options['fields']['field_ne_body']['id'] = 'field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['table'] = 'field_data_field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['field'] = 'field_ne_body';
    $handler->display->display_options['fields']['field_ne_body']['label'] = '';
    $handler->display->display_options['fields']['field_ne_body']['element_label_colon'] = FALSE;
    /* Field: Content: All taxonomy terms */
    $handler->display->display_options['fields']['term_node_tid']['id'] = 'term_node_tid';
    $handler->display->display_options['fields']['term_node_tid']['table'] = 'node';
    $handler->display->display_options['fields']['term_node_tid']['field'] = 'term_node_tid';
    $handler->display->display_options['fields']['term_node_tid']['label'] = '';
    $handler->display->display_options['fields']['term_node_tid']['exclude'] = TRUE;
    $handler->display->display_options['fields']['term_node_tid']['element_label_colon'] = FALSE;
    $handler->display->display_options['fields']['term_node_tid']['limit'] = TRUE;
    $handler->display->display_options['fields']['term_node_tid']['vocabularies'] = array(
      'faq_categories' => 'faq_categories',
      'classification' => 0,
      'tags' => 0,
    );
    $handler->display->display_options['defaults']['filter_groups'] = FALSE;
    $handler->display->display_options['defaults']['filters'] = FALSE;
    /* Filter criterion: Content: Published */
    $handler->display->display_options['filters']['status']['id'] = 'status';
    $handler->display->display_options['filters']['status']['table'] = 'node';
    $handler->display->display_options['filters']['status']['field'] = 'status';
    $handler->display->display_options['filters']['status']['value'] = 1;
    $handler->display->display_options['filters']['status']['group'] = 1;
    $handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
    /* Filter criterion: Content: Type */
    $handler->display->display_options['filters']['type']['id'] = 'type';
    $handler->display->display_options['filters']['type']['table'] = 'node';
    $handler->display->display_options['filters']['type']['field'] = 'type';
    $handler->display->display_options['filters']['type']['value'] = array(
      'nexteuropa_faq' => 'nexteuropa_faq',
    );
    /* Filter criterion: Content: Categories (field_ne_faq_categories) */
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['id'] = 'field_ne_faq_categories_tid';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['table'] = 'field_data_field_ne_faq_categories';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['field'] = 'field_ne_faq_categories_tid';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['value'] = array();
    $term = taxonomy_get_term_by_name('Cooperation');
    if ((isset($term)) && (!empty($term))) {
      $filter_term = current($term);
      $tid_term = $filter_term->tid;
      $handler->display->display_options['filters']['field_ne_faq_categories_tid']['value'][$tid_term] = $tid_term;
    }
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['type'] = 'select';
    $handler->display->display_options['filters']['field_ne_faq_categories_tid']['vocabulary'] = 'faq_categories';
    $handler->display->display_options['path'] = 'tools/faq/cooperation';
    /*
    $term = taxonomy_get_term_by_name('Cooperation');
    if ((isset($term)) && (!empty($term))) {
      $filter_term = current($term);
      $tid_term = $filter_term->tid;
      $views['ne_faq']->display['page_faq_cooperation']->display_options['filters']['field_ne_faq_categories_tid']['value'][$tid_term] = $tid_term;
    }
    */

  }
}

/**
 * Implements hook_COMPONENT_alter().
 */
function farnet_faq_strongarm_alter(&$variables) {
  if (isset($variables['comment_nexteuropa_faq'])) {
    $variables['comment_nexteuropa_faq']->value = 1;
  }
}
