<?php
/**
 * @file
 * Code for the Farnet FAQ feature.
 */

include_once 'farnet_faq.features.inc';

/**
 * Implements hook_field_group_info_alter().
 */
function farnet_faq_field_group_info_alter($groups) {
  if (!empty($groups['group_ne_faq_content|node|nexteuropa_faq|form'])) {
    $groups['group_ne_faq_content|node|nexteuropa_faq|form']->data['children'][] = 'field_id';
    $groups['group_ne_faq_content|node|nexteuropa_faq|form']->data['children'][] = 'field_short_title';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function farnet_faq_form_nexteuropa_faq_node_form_alter(&$form, &$form_state, $form_id) {
  $path = drupal_get_path('module', 'farnet_faq');
  $form['#attached']['js'] = drupal_add_js(
    $path . '/farnet_faq.js',
    array(
      'type' => 'file',
      'scope' => 'footer',
      'weight' => 100,
    )
  );
}

/**
 * Implements hook_COMPONENT_alter().
 *
 * COMPONENT = field_default_field_instances.
 */
function farnet_faq_field_default_field_instances_alter(&$fields) {

  if (isset($fields['node-nexteuropa_faq-title_field'])) {
    if (isset($fields['node-nexteuropa_faq-title_field']['display'])) {
      $fields['node-nexteuropa_faq-title_field']['display']['teaser']['label'] = "hidden";
      $fields['node-nexteuropa_faq-title_field']['display']['teaser']['module'] = "text";
      $fields['node-nexteuropa_faq-title_field']['display']['teaser']['settings'] = array();
      $fields['node-nexteuropa_faq-title_field']['display']['teaser']['type'] = "text_plain";
      /* $fields['node-nexteuropa_faq-title_field']['display']['teaser']['type'] = "title_linked";*/
      $fields['node-nexteuropa_faq-title_field']['display']['teaser']['weight'] = 0;
    }
  }

  if (isset($fields['node-nexteuropa_faq-field_ne_body'])) {
    if (isset($fields['node-nexteuropa_faq-field_ne_body']['display'])) {
      $fields['node-nexteuropa_faq-field_ne_body']['display']['teaser']['label'] = "hidden";
      $fields['node-nexteuropa_faq-field_ne_body']['display']['teaser']['module'] = "text";
      $fields['node-nexteuropa_faq-field_ne_body']['display']['teaser']['settings'] = array();
      $fields['node-nexteuropa_faq-field_ne_body']['display']['teaser']['type'] = "text_default";
      $fields['node-nexteuropa_faq-field_ne_body']['display']['teaser']['weight'] = 2;
    }
  }
}
