<?php

/**
 * @file
 * Code for the MyFarnet Event feature.
 */

include_once 'myfarnet_event.features.inc';

/**
 * Implements hook_menu().
 */
function myfarnet_event_menu() {
  $items = array();

  $items['community/%community/events'] = array(
    'title' => 'Events',
    'page callback' => 'farnet_communities_display_views',
    'page arguments' => array('my_farnet_event', 'page_1', 1),
    'access callback' => '_farnet_communities_ct_page_access',
    'access arguments' => array('access private area', 1, 'myfarnet_event'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-community-menu',
    'weight' => 4,
    'file' => 'farnet_communities.callback.inc',
    'file path' => drupal_get_path('module', 'farnet_communities'),
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function myfarnet_event_form_myfarnet_event_node_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  $user_roles = array_values($user->roles);
  if (!in_array('FSU Administrator', $user_roles) && !in_array('administrator', $user_roles)) {
    $form['revision_information']['#access'] = FALSE;
    $form['group_content_access']['#access'] = FALSE;
    $form['og_group_ref']['#access'] = FALSE;
  }

  $path = drupal_get_path('module', 'myfarnet_event');
  $form['#attached']['js'] = [
    [
      'data' => $path . '/js/myfarnet_event.js',
      'type' => 'file',
      'scope' => 'footer',
      'weight' => 100,
    ],
  ];
}

/**
 * Implements hook_COMPONENT_alter().
 *
 * COMPONENT = field_default_field_bases.
 */
function myfarnet_event_field_default_field_bases_alter(&$fields) {
  if (isset($fields['field_related_documents'])) {
    $fields['field_related_documents']['settings']['display_default'] = 0;
    $fields['field_related_documents']['settings']['display_field'] = 0;
  }
}
