<?php

/**
 * @file
 * Code for the Farnet News feature.
 */

include_once 'farnet_news.features.inc';

/**
 * Implements hook_COMPONENT_alter().
 *
 * COMPONENT = field_default_field_instances.
 */
function farnet_news_field_default_field_instances_alter(&$fields) {

  if (isset($fields['node-nexteuropa_news-title_field'])) {
    if (isset($fields['node-nexteuropa_news-title_field']['display'])) {
      $fields['node-nexteuropa_news-title_field']['display']['teaser']['label'] = "hidden";
      $fields['node-nexteuropa_news-title_field']['display']['teaser']['module'] = "text";
      $fields['node-nexteuropa_news-title_field']['display']['teaser']['settings'] = array();
      $fields['node-nexteuropa_news-title_field']['display']['teaser']['type'] = "text_plain";
      $fields['node-nexteuropa_news-title_field']['display']['teaser']['weight'] = 0;
    }
  }

  if (isset($fields['node-nexteuropa_news-field_abstract'])) {
    $fields['node-nexteuropa_news-field_abstract']['widget']['settings']['maxlength_js'] = '400';
    $fields['node-nexteuropa_news-field_abstract']['widget']['settings']['maxlength_js_label'] = 'Content limited to @limit characters, remaining: <strong>@remaining</strong>';
    $fields['node-nexteuropa_news-field_abstract']['widget']['settings']['maxlength_js_label_summary'] = 'Content limited to @limit characters, remaining: <strong>@remaining</strong>';
    if (isset($fields['node-nexteuropa_news-field_abstract']['display'])) {
      $fields['node-nexteuropa_news-field_abstract']['display']['teaser']['label'] = "hidden";
      $fields['node-nexteuropa_news-field_abstract']['display']['teaser']['module'] = "text";
      $fields['node-nexteuropa_news-field_abstract']['display']['teaser']['settings'] = array();
      $fields['node-nexteuropa_news-field_abstract']['display']['teaser']['type'] = "text_plain";
      $fields['node-nexteuropa_news-field_abstract']['display']['teaser']['weight'] = 2;

      $fields['node-nexteuropa_news-field_abstract']['display']['newsletter']['label'] = "hidden";
      $fields['node-nexteuropa_news-field_abstract']['display']['newsletter']['module'] = "text";
      $fields['node-nexteuropa_news-field_abstract']['display']['newsletter']['settings'] = array();
      $fields['node-nexteuropa_news-field_abstract']['display']['newsletter']['type'] = "text_plain";
      $fields['node-nexteuropa_news-field_abstract']['display']['newsletter']['weight'] = 0;

      $fields['node-nexteuropa_news-field_abstract']['display']['newsletter_news_list']['label'] = "hidden";
      $fields['node-nexteuropa_news-field_abstract']['display']['newsletter_news_list']['module'] = "text";
      $fields['node-nexteuropa_news-field_abstract']['display']['newsletter_news_list']['settings'] = array();
      $fields['node-nexteuropa_news-field_abstract']['display']['newsletter_news_list']['type'] = "text_plain";
      $fields['node-nexteuropa_news-field_abstract']['display']['newsletter_news_list']['weight'] = 0;
    }
  }

  if (isset($fields['node-nexteuropa_news-field_image'])) {
    if (isset($fields['node-nexteuropa_news-field_image']['display'])) {
      $fields['node-nexteuropa_news-field_image']['display']['newsletter']['label'] = "hidden";
      $fields['node-nexteuropa_news-field_image']['display']['newsletter']['module'] = "image";
      $fields['node-nexteuropa_news-field_image']['display']['newsletter']['settings']['image_link'] = "";
      $fields['node-nexteuropa_news-field_image']['display']['newsletter']['settings']['image_style'] = "";
      $fields['node-nexteuropa_news-field_image']['display']['newsletter']['type'] = "image";
      $fields['node-nexteuropa_news-field_image']['display']['newsletter']['weight'] = 0;

      $fields['node-nexteuropa_news-field_image']['display']['newsletter_news_list']['label'] = "hidden";
      $fields['node-nexteuropa_news-field_image']['display']['newsletter_news_list']['settings'] = array();
      $fields['node-nexteuropa_news-field_image']['display']['newsletter_news_list']['type'] = "hidden";
      $fields['node-nexteuropa_news-field_image']['display']['newsletter_news_list']['weight'] = 0;
    }
  }
}

/**
 * Implements hook_COMPONENT_alter().
 */
function farnet_news_strongarm_alter(&$variables) {
  if (isset($variables['pathauto_node_nexteuropa_news_pattern'])) {
    $variables['pathauto_node_nexteuropa_news_pattern']->value = "news-events/news/[node:source:title]";
  }
}

/**
 * Implements hook_node_view().
 * @todo remove if CT Nexteuropa News corrected on platform
 */
function farnet_news_node_view($node, $view_mode, $langcode = NULL) {
  if ($node->type === 'nexteuropa_news' && $view_mode === 'teaser' && !empty($node->content['title_field'][0]['#markup'])) {
    global $base_url; 
    $title = $node->content['title_field']['#items'][0]['value'];
    $node_url = drupal_get_path_alias('node/' . $node->nid);
    $node->content['title_field'][0]['#markup'] = '<h2><a href="' . $base_url . '/' . $node_url . '" class="">' . $title . '</a></h2>';
  }
  return $node;
}
