<?php

/**
 * @file
 * Code for the Farnet Factsheet Flag feature.
 */

include_once 'farnet_factsheet_flag.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function farnet_factsheet_flag_form_factsheet_flag_node_form_alter(&$form, &$form_state, $form_id) {
  $path = drupal_get_path('module', 'farnet_factsheet_flag');
  $form['#attached']['js'] = [
    [
      'data' => $path . '/js/farnet_factsheet_flag.js',
      'type' => 'file',
      'scope' => 'footer',
      'weight' => 100,
    ],
  ];
}
