<?php
/**
 * @file
 * Code for the Farnet Article feature.
 */

include_once 'farnet_article.features.inc';

 
/**
 * Implements hook_COMPONENT_alter().
 *
 * COMPONENT = field_default_field_instances.
 */
function farnet_article_field_default_field_instances_alter(&$fields) {
  if (isset($fields['node-article-body'])) {
    unset ($fields['node-article-body']);
  }
}


/**
 * Implements hook_COMPONENT_alter().
 *
 * COMPONENT = field_group_info.
 */
function farnet_article_field_group_info_alter($groups) {
  if (!empty($groups['group_article_content|node|article|form'])) {
    if ($key = array_search("field_body", $groups['group_article_content|node|article|form']->data['children'])){
      unset ($groups['group_article_content|node|article|form']->data['children'][$key]);
    }
    $groups['group_article_content|node|article|form']->data['children'][] = 'field_ne_body';
    $groups['group_article_content|node|article|form']->data['children'][] = 'field_page';
  }
}