<?php

/**
 * @file
 * Code for the Farnet Article feature.
 */

include_once 'farnet_article.features.inc';

/**
 * Implements hook_node_info_alter().
 */
function farnet_article_node_info_alter(&$items) {
  if (isset($items['article'])) {
    unset($items['article']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function farnet_article_form_node_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'farnet_article_node_form') {
    $form['field_ne_body'][LANGUAGE_NONE]['#required'] = FALSE;
    $form['field_ne_body'][LANGUAGE_NONE][0]['#required'] = FALSE;
  }
}
